# Generated by Django 5.2 on 2025-01-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ourprojects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="project",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="reference",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="person",
            name="aux",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="aux",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="aux",
            field=models.JSONField(default=None, null=True),
        ),
    ]
