# Generated by Django 5.2 on 2024-11-15 08:55

import django.db.models.deletion
import lnschema_core.fields
import lnschema_core.ids
import lnschema_core.models
import lnschema_core.users
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lnschema_core",
            "0069_alter_artifact__accessor_alter_artifact__hash_type_and_more",
        ),
        ("ourprojects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifactproject",
            name="artifact",
            field=lnschema_core.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links_project",
                to="lnschema_core.artifact",
            ),
        ),
        migrations.AlterField(
            model_name="artifactproject",
            name="created_at",
            field=lnschema_core.fields.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="artifactproject",
            name="created_by",
            field=lnschema_core.fields.ForeignKey(
                blank=True,
                default=lnschema_core.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lnschema_core.user",
            ),
        ),
        migrations.AlterField(
            model_name="artifactproject",
            name="feature",
            field=lnschema_core.fields.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="links_artifactproject",
                to="lnschema_core.feature",
            ),
        ),
        migrations.AlterField(
            model_name="artifactproject",
            name="feature_ref_is_name",
            field=lnschema_core.fields.BooleanField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="artifactproject",
            name="label_ref_is_name",
            field=lnschema_core.fields.BooleanField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="artifactproject",
            name="project",
            field=lnschema_core.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="links_artifact",
                to="ourprojects.project",
            ),
        ),
        migrations.AlterField(
            model_name="artifactproject",
            name="run",
            field=lnschema_core.fields.ForeignKey(
                blank=True,
                default=lnschema_core.models.current_run,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lnschema_core.run",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="abbr",
            field=lnschema_core.fields.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=32,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=lnschema_core.fields.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_by",
            field=lnschema_core.fields.ForeignKey(
                blank=True,
                default=lnschema_core.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lnschema_core.user",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=lnschema_core.fields.CharField(
                blank=True, db_index=True, default=None, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="run",
            field=lnschema_core.fields.ForeignKey(
                blank=True,
                default=lnschema_core.models.current_run,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lnschema_core.run",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="uid",
            field=lnschema_core.fields.CharField(
                blank=True,
                default=lnschema_core.ids.base62_12,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=lnschema_core.fields.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
